"""fg-zettelkasten — build a topic-anchored Obsidian Zettelkasten from the toread feed.

Usage:
    python -m src.main refresh-topics
    python -m src.main bootstrap [--limit N]
    python -m src.main update [--recluster]
    python -m src.main recluster
    python -m src.main slack-test <bibtex-key>

See README.md and the implementation plan for architecture detail.
"""
from __future__ import annotations

import argparse
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import yaml

try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:  # python-dotenv optional at import time
    pass

ROOT = Path(__file__).resolve().parent.parent


def load_config(path: str = "config.yml") -> dict:
    cfg_path = Path(path)
    if not cfg_path.is_absolute():
        cfg_path = ROOT / cfg_path
    with open(cfg_path) as fh:
        return yaml.safe_load(fh)


# --- helpers --------------------------------------------------------------


def _abs(rel: str) -> str:
    """Resolve a config-relative path against the project root."""
    p = Path(rel)
    return str(p if p.is_absolute() else ROOT / p)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _claude(cfg: dict):
    """Build the Claude SDK wrapper from config (lazy import keeps --help cheap)."""
    from .claude_client import ClaudeClient

    cc = cfg["claude"]
    return ClaudeClient(
        summary_model=cc["summary_model"],
        reasoning_model=cc["reasoning_model"],
    )


def _drive_client(cfg: dict):
    """Build a DriveClient from the environment, or None when unavailable.

    The Google-Drive PDF source is optional: without it papers fall back to
    abstract-only summaries rather than failing the run.
    """
    creds = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    folder = os.environ.get("GOOGLE_DRIVE_FOLDER_ID")
    if not creds or not folder or not Path(creds).exists():
        print("WARN: Google Drive not configured — using abstract-only summaries")
        return None
    try:
        from .drive_client import DriveClient

        return DriveClient(creds, folder)
    except Exception as exc:  # noqa: BLE001 - Drive is optional, never fatal
        print(f"WARN: could not initialise Drive client ({exc}) — abstract-only")
        return None


def _pdf_text(cfg: dict, drive, paper):
    """Extracted full PDF text for `paper`, cached transiently in data/.cache/."""
    cache_dir = Path(_abs(cfg["paths"]["cache_dir"]))
    cache_file = cache_dir / f"{paper.bibtex_key}.txt"
    if cache_file.exists():
        return cache_file.read_text(encoding="utf-8")
    if drive is None:
        return None
    text = drive.get_pdf_text(
        paper, max_chars=cfg["claude"].get("max_pdf_chars", 80000)
    )
    if text:
        # Some malformed PDFs yield lone surrogate code points that cannot be
        # UTF-8 encoded — neither for the cache file nor the Claude API request.
        text = text.encode("utf-8", "ignore").decode("utf-8")
        cache_dir.mkdir(parents=True, exist_ok=True)
        cache_file.write_text(text, encoding="utf-8")
    return text


def _related_keys(state: dict, paper_id: str, topics: list[str]) -> list[str]:
    """Bibtex keys of other papers sharing at least one topic with `paper_id`."""
    wanted = set(topics)
    out = []
    for pid, entry in state["papers"].items():
        if pid == paper_id:
            continue
        if wanted & set(entry.get("topics", [])):
            out.append(pid.split(":", 1)[-1])
    return out


def _prune_stale_notes(notes_dir: Path, keep: set[str]) -> list[str]:
    """Delete *.md files in `notes_dir` whose slug is not in `keep`.

    Derived note directories (Topics/, Structures/) are regenerated by
    slug-named filename. Topic slugs are re-synthesized on every run, so a
    slug that disappears would otherwise leave an orphan note behind; pruning
    to exactly the slugs just written keeps reruns free of stale notes.
    """
    if not notes_dir.is_dir():
        return []
    removed = [f.name for f in notes_dir.glob("*.md") if f.stem not in keep]
    for name in removed:
        (notes_dir / name).unlink()
    return removed


def _regenerate_topic_notes(cfg: dict, register: list[dict], state: dict) -> None:
    """Deterministically rewrite every Topics/*.md register entry note."""
    from . import note_builder

    vault = _abs(cfg["vault"]["path"])
    topics_dir = cfg["vault"]["topics_dir"]
    written: set[str] = set()
    for topic in register:
        members = [
            pid.split(":", 1)[-1]
            for pid, entry in state["papers"].items()
            if topic["slug"] in entry.get("topics", [])
        ]
        content = note_builder.build_topic_note(topic, members)
        note_builder.write_note(vault, topics_dir, topic["slug"], content)
        written.add(topic["slug"])
    stale = _prune_stale_notes(Path(vault) / topics_dir, written)
    if stale:
        print(f"  pruned {len(stale)} stale topic note(s)")


def _rewrite_note_topics(note_path: str, topics: list[str]) -> None:
    """Update a paper note's frontmatter `topics:` line in place (no LLM)."""
    p = Path(note_path)
    if not p.exists():
        return
    lines = p.read_text(encoding="utf-8").splitlines()
    new_line = f"topics: [{', '.join(topics)}]"
    for i, line in enumerate(lines):
        if line.startswith("topics:"):
            lines[i] = new_line
            break
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _sanitize_vault_links(cfg: dict, verbose: bool = False) -> dict:
    """Repair / de-link unresolved [[wikilinks]] in paper and structure notes.

    LLM-written "Connections" sometimes link bibtex keys absent from the vault
    (year-typos or invented citations). This pass resolves every wikilink
    against the actual note filenames on disk — no LLM, idempotent.
    """
    from . import note_builder

    vault = Path(_abs(cfg["vault"]["path"]))
    papers_dir = vault / cfg["vault"]["papers_dir"]
    structures_dir = vault / cfg["vault"]["structures_dir"]
    topics_dir = vault / cfg["vault"]["topics_dir"]

    known = {f.stem for f in papers_dir.glob("*.md")}
    known |= {f.stem for f in topics_dir.glob("*.md")}

    notes_changed = 0
    repaired: dict[str, str] = {}
    delinked: set[str] = set()
    for note_dir in (papers_dir, structures_dir):
        for note in sorted(note_dir.glob("*.md")):
            original = note.read_text(encoding="utf-8")
            fixed, changes = note_builder.sanitize_links(original, known)
            if not changes:
                continue
            note.write_text(fixed, encoding="utf-8")
            notes_changed += 1
            for change in changes:
                if change[0] == "repaired":
                    repaired[change[1]] = change[2]
                else:
                    delinked.add(change[1])
            if verbose:
                detail = ", ".join(
                    f"{c[1]}->{c[2]}" if c[0] == "repaired" else f"-{c[1]}"
                    for c in changes
                )
                print(f"  {note.name}: {detail}")
    return {
        "notes_changed": notes_changed,
        "repaired": repaired,
        "delinked": sorted(delinked),
    }


# --- commands -------------------------------------------------------------
# Each command is a thin orchestrator over src/* modules.


def _build_register(cfg: dict, claude) -> list[dict]:
    """Fetch the live github.io signals and synthesize the anchor topics."""
    from . import topics_client

    signals = topics_client.fetch_signals(
        cfg["inputs"]["github_io_base"], cfg["inputs"]["github_io_signals"]
    )
    if not signals:
        raise RuntimeError("no research-agenda signals could be fetched")
    return topics_client.synthesize_register(signals, claude, cfg["topics"])


def _topic_members(slug: str, state: dict, papers_by_key: dict) -> list:
    """The `Paper` objects assigned to `slug`, in feed order."""
    return [
        papers_by_key[key]
        for pid, entry in state["papers"].items()
        for key in (pid.split(":", 1)[-1],)
        if slug in entry.get("topics", []) and key in papers_by_key
    ]


def _generate_structure_notes(cfg, register, state, papers_by_key, summaries, claude):
    """Render one Structures/<slug>.md hub note per non-empty topic."""
    from . import note_builder

    vault = _abs(cfg["vault"]["path"])
    structures_dir = cfg["vault"]["structures_dir"]
    written: set[str] = set()
    for topic in register:
        members = _topic_members(topic["slug"], state, papers_by_key)
        if not members:
            continue
        note = note_builder.build_structure_note(
            topic, members, summaries, claude, claude.reasoning_model
        )
        note_builder.write_note(vault, structures_dir, topic["slug"], note)
        written.add(topic["slug"])
    stale = _prune_stale_notes(Path(vault) / structures_dir, written)
    if stale:
        print(f"  pruned {len(stale)} stale structure note(s)")


def cmd_refresh_topics(cfg: dict, args) -> int:
    """Rebuild the topic register from the live github.io research-agenda signals."""
    from . import topics_client, state as state_mod

    claude = _claude(cfg)
    register = _build_register(cfg, claude)

    # Anchor topics are re-synthesized; emergent topics (created at
    # bootstrap/recluster) are carried over so existing assignments survive.
    topics_file = _abs(cfg["paths"]["topics_file"])
    emergent = [t for t in topics_client.load_topics(topics_file) if t.get("is_emergent")]
    register = register + emergent

    topics_client.save_topics(register, topics_file)
    state = state_mod.load_state(_abs(cfg["paths"]["state_file"]))
    _regenerate_topic_notes(cfg, register, state)
    print(f"refresh-topics: {len(register)} topics written to the register")
    return 0


def cmd_bootstrap(cfg: dict, args) -> int:
    """Process the whole archive: register, per-paper notes, themes, hub notes."""
    from . import (
        feed_client,
        episodes_client,
        topics_client,
        summarizer,
        themes,
        note_builder,
        state as state_mod,
    )

    claude = _claude(cfg)
    drive = _drive_client(cfg)

    register = _build_register(cfg, claude)
    papers = feed_client.fetch_feed(cfg["inputs"]["feed_url"])
    episodes = episodes_client.fetch_episode_audio(cfg["inputs"]["episodes_url"])
    if args.limit:
        papers = papers[: args.limit]
    print(f"bootstrap: {len(papers)} papers, {len(register)} anchor topics")

    summaries_dir = _abs(cfg["paths"]["summaries_dir"])
    papers_dir = cfg["vault"]["papers_dir"]
    state = {"papers": {}, "last_full_cluster": _now(), "papers_since_cluster": 0}
    summaries: dict[str, dict] = {}

    # 1. summarize every paper (full PDF when available, else abstract).
    #    Reuse an existing summary when present so an interrupted run can be
    #    resumed without re-billing the per-paper Claude pass.
    for i, paper in enumerate(papers, 1):
        cached = summarizer.load_summary(summaries_dir, paper.bibtex_key)
        if cached is not None:
            print(f"  [{i}/{len(papers)}] cached   {paper.bibtex_key}")
            summary = cached
        else:
            print(f"  [{i}/{len(papers)}] summarize {paper.bibtex_key}")
            text = _pdf_text(cfg, drive, paper)
            summary = summarizer.summarize_paper(
                paper, text, claude, claude.summary_model
            )
            summarizer.save_summary(summary, summaries_dir, paper.bibtex_key)
        summaries[paper.bibtex_key] = summary
        podcast = paper.id in episodes
        state["papers"][paper.id] = {
            "note_path": f"{papers_dir}/{paper.bibtex_key}.md",
            "topics": [],
            "pdf_source": summary["pdf_source"],
            "content_hash": state_mod.content_hash(paper.abstract, podcast),
            "podcast_linked": podcast,
            "last_processed": _now(),
        }

    # 2. topic-anchored assignment + emergent sub-themes.
    unassigned = []
    for paper in papers:
        slugs = themes.assign_paper(
            paper, summaries[paper.bibtex_key], register, claude, claude.reasoning_model
        )
        state["papers"][paper.id]["topics"] = slugs
        if not slugs:
            unassigned.append(paper)

    emergent = themes.find_emergent(
        unassigned, summaries, claude, claude.reasoning_model,
        cfg["topics"]["emergent_min_papers"],
    )
    for topic in emergent:
        register.append(
            {
                "slug": topic["slug"],
                "name": topic["name"],
                "description": topic["description"],
                "source_signals": [],
                "is_emergent": True,
            }
        )
        for key in topic["members"]:
            entry = state["papers"].get(f"bibtex:{key}")
            if entry is not None:
                entry["topics"].append(topic["slug"])

    topics_client.save_topics(register, _abs(cfg["paths"]["topics_file"]))
    print(f"  {len(unassigned)} unassigned, {len(emergent)} emergent topic(s)")

    # 3. render paper notes, then regenerate Topics/ and Structures/.
    vault = _abs(cfg["vault"]["path"])
    for paper in papers:
        entry = state["papers"][paper.id]
        related = _related_keys(state, paper.id, entry["topics"])
        note = note_builder.build_paper_note(
            paper, summaries[paper.bibtex_key], entry["topics"], related,
            episodes.get(paper.id), claude, claude.reasoning_model,
        )
        note_builder.write_note(vault, papers_dir, paper.bibtex_key, note)

    _regenerate_topic_notes(cfg, register, state)
    papers_by_key = {p.bibtex_key: p for p in papers}
    _generate_structure_notes(cfg, register, state, papers_by_key, summaries, claude)

    sanitised = _sanitize_vault_links(cfg)
    print(
        f"  link sanitiser: {len(sanitised['repaired'])} repaired, "
        f"{len(sanitised['delinked'])} de-linked"
    )

    state_mod.save_state(state, _abs(cfg["paths"]["state_file"]))
    print("bootstrap: done")
    return 0


def cmd_update(cfg: dict, args) -> int:
    """Daily incremental run: new/changed papers only."""
    from . import (
        feed_client,
        episodes_client,
        topics_client,
        summarizer,
        themes,
        note_builder,
        slack_client,
        state as state_mod,
    )

    claude = _claude(cfg)
    drive = _drive_client(cfg)

    # Post a digest of each newly-added paper to Slack only when the feature is
    # enabled in config *and* a webhook secret is present (so local runs and
    # contributors without the secret are unaffected).
    post_to_slack = bool(cfg.get("slack", {}).get("enabled")) and bool(
        os.environ.get("SLACK_WEBHOOK_URL")
    )

    topics_file = _abs(cfg["paths"]["topics_file"])
    register = topics_client.load_topics(topics_file)
    state = state_mod.load_state(_abs(cfg["paths"]["state_file"]))
    if not register:
        print("update: no topic register — run refresh-topics or bootstrap first")
        return 1

    papers = feed_client.fetch_feed(cfg["inputs"]["feed_url"])
    episodes = episodes_client.fetch_episode_audio(cfg["inputs"]["episodes_url"])
    summaries_dir = _abs(cfg["paths"]["summaries_dir"])
    papers_dir = cfg["vault"]["papers_dir"]
    vault = _abs(cfg["vault"]["path"])

    # Diff the feed against state by id and by content hash.
    new_papers, changed_papers = [], []
    for paper in papers:
        podcast = paper.id in episodes
        new_hash = state_mod.content_hash(paper.abstract, podcast)
        entry = state["papers"].get(paper.id)
        if entry is None:
            new_papers.append(paper)
        elif entry.get("content_hash") != new_hash:
            changed_papers.append(paper)
    print(f"update: {len(new_papers)} new, {len(changed_papers)} changed")

    summaries: dict[str, dict] = {}

    # New papers: summarize + assign to existing register topics.
    for paper in new_papers:
        text = _pdf_text(cfg, drive, paper)
        summary = summarizer.summarize_paper(
            paper, text, claude, claude.summary_model
        )
        summarizer.save_summary(summary, summaries_dir, paper.bibtex_key)
        summaries[paper.bibtex_key] = summary
        slugs = themes.assign_paper(
            paper, summary, register, claude, claude.reasoning_model
        )
        podcast = paper.id in episodes
        state["papers"][paper.id] = {
            "note_path": f"{papers_dir}/{paper.bibtex_key}.md",
            "topics": slugs,
            "pdf_source": summary["pdf_source"],
            "content_hash": state_mod.content_hash(paper.abstract, podcast),
            "podcast_linked": podcast,
            "slack_posted": False,
            "last_processed": _now(),
        }

    # Changed papers: refresh the state hash (e.g. a podcast episode appeared).
    for paper in changed_papers:
        podcast = paper.id in episodes
        entry = state["papers"][paper.id]
        entry["podcast_linked"] = podcast
        entry["content_hash"] = state_mod.content_hash(paper.abstract, podcast)
        entry["last_processed"] = _now()

    # Re-render the note for every new or changed paper.
    touched = new_papers + changed_papers
    for paper in touched:
        entry = state["papers"][paper.id]
        summary = summaries.get(paper.bibtex_key) or summarizer.load_summary(
            summaries_dir, paper.bibtex_key
        )
        if summary is None:
            print(f"  WARN: no summary for {paper.bibtex_key}, skipping note")
            continue
        related = _related_keys(state, paper.id, entry["topics"])
        note = note_builder.build_paper_note(
            paper, summary, entry["topics"], related,
            episodes.get(paper.id), claude, claude.reasoning_model,
        )
        note_builder.write_note(vault, papers_dir, paper.bibtex_key, note)

        # Post a Slack digest for genuinely-new papers only, once each. The
        # `slack_posted` flag makes this idempotent across cron retries / a
        # crash before save_state; a Slack failure is logged, never fatal.
        if post_to_slack and paper in new_papers and not entry.get("slack_posted"):
            try:
                posted = slack_client.post_paper(
                    os.environ["SLACK_WEBHOOK_URL"], paper, summary,
                    entry["topics"], episodes.get(paper.id),
                )
            except Exception as exc:  # noqa: BLE001 - Slack must never break the build
                posted = False
                print(f"  slack: unexpected error for {paper.bibtex_key} ({exc})")
            if posted:
                entry["slack_posted"] = True
                # Persist immediately: if a later paper in this loop crashes the
                # run before the save_state at the end, this paper must not be
                # re-posted on the next cron retry.
                state_mod.save_state(state, _abs(cfg["paths"]["state_file"]))
                print(f"  slack: posted {paper.bibtex_key} to #toread")
            time.sleep(0.5)  # incoming-webhook rate limit is ~1/s

    state["papers_since_cluster"] = (
        state.get("papers_since_cluster", 0) + len(new_papers)
    )
    if touched:
        _regenerate_topic_notes(cfg, register, state)

    threshold = cfg["processing"]["recluster_threshold"]
    do_recluster = args.recluster or state["papers_since_cluster"] >= threshold
    state_mod.save_state(state, _abs(cfg["paths"]["state_file"]))

    if not touched and not do_recluster:
        print("update: nothing to do")
        return 0

    if do_recluster:
        _recluster(cfg, claude, drive)

    sanitised = _sanitize_vault_links(cfg)
    print(
        f"  link sanitiser: {len(sanitised['repaired'])} repaired, "
        f"{len(sanitised['delinked'])} de-linked"
    )
    print("update: done")
    return 0


def _recluster(cfg: dict, claude, drive) -> None:
    """Full re-cluster: rebuild the register, re-assign every processed paper,
    regenerate Topics/ and Structures/. Paper note bodies are not re-summarised
    (cost) — only their frontmatter `topics:` is updated in place."""
    from . import feed_client, topics_client, summarizer, themes, state as state_mod

    print("recluster: rebuilding the register and re-clustering the archive")
    register = _build_register(cfg, claude)
    state = state_mod.load_state(_abs(cfg["paths"]["state_file"]))
    summaries_dir = _abs(cfg["paths"]["summaries_dir"])

    papers = [
        p for p in feed_client.fetch_feed(cfg["inputs"]["feed_url"])
        if p.id in state["papers"]
    ]
    summaries: dict[str, dict] = {}
    for paper in papers:
        s = summarizer.load_summary(summaries_dir, paper.bibtex_key)
        if s is not None:
            summaries[paper.bibtex_key] = s

    unassigned = []
    for paper in papers:
        summary = summaries.get(paper.bibtex_key)
        if summary is None:
            continue
        slugs = themes.assign_paper(
            paper, summary, register, claude, claude.reasoning_model
        )
        state["papers"][paper.id]["topics"] = slugs
        if not slugs:
            unassigned.append(paper)

    emergent = themes.find_emergent(
        unassigned, summaries, claude, claude.reasoning_model,
        cfg["topics"]["emergent_min_papers"],
    )
    for topic in emergent:
        register.append(
            {
                "slug": topic["slug"],
                "name": topic["name"],
                "description": topic["description"],
                "source_signals": [],
                "is_emergent": True,
            }
        )
        for key in topic["members"]:
            entry = state["papers"].get(f"bibtex:{key}")
            if entry is not None:
                entry["topics"].append(topic["slug"])

    topics_client.save_topics(register, _abs(cfg["paths"]["topics_file"]))

    # Update each paper note's frontmatter topics in place (no re-summary).
    vault = Path(_abs(cfg["vault"]["path"]))
    for paper in papers:
        entry = state["papers"][paper.id]
        _rewrite_note_topics(str(vault / entry["note_path"]), entry["topics"])

    _regenerate_topic_notes(cfg, register, state)
    papers_by_key = {p.bibtex_key: p for p in papers}
    _generate_structure_notes(cfg, register, state, papers_by_key, summaries, claude)

    state["last_full_cluster"] = _now()
    state["papers_since_cluster"] = 0
    state_mod.save_state(state, _abs(cfg["paths"]["state_file"]))
    print(f"recluster: {len(register)} topics, {len(emergent)} emergent")


def cmd_recluster(cfg: dict, args) -> int:
    """Force a full re-cluster of the whole archive."""
    args.recluster = True
    return cmd_update(cfg, args)


def cmd_fix_links(cfg: dict, args) -> int:
    """Repair / de-link unresolved [[wikilinks]] across the vault."""
    result = _sanitize_vault_links(cfg, verbose=True)
    print(
        f"fix-links: {result['notes_changed']} note(s) updated — "
        f"{len(result['repaired'])} target(s) repaired, "
        f"{len(result['delinked'])} de-linked"
    )
    for old, new in sorted(result["repaired"].items()):
        print(f"  repaired:  {old} -> {new}")
    for target in result["delinked"]:
        print(f"  de-linked: {target}")
    return 0


def cmd_slack_test(cfg: dict, args) -> int:
    """Post one paper's digest to Slack — verify Block Kit rendering / re-post."""
    from . import (
        feed_client, episodes_client, summarizer, slack_client,
        state as state_mod,
    )

    webhook = os.environ.get("SLACK_WEBHOOK_URL")
    if not webhook:
        print("slack-test: SLACK_WEBHOOK_URL is not set")
        return 1

    key = args.bibtex_key
    papers = feed_client.fetch_feed(cfg["inputs"]["feed_url"])
    paper = next((p for p in papers if p.bibtex_key == key), None)
    if paper is None:
        print(f"slack-test: no paper with bibtex key {key!r} in the feed")
        return 1

    summary = summarizer.load_summary(_abs(cfg["paths"]["summaries_dir"]), key)
    if summary is None:
        print(f"slack-test: no cached summary for {key} — run `update` first")
        return 1

    state = state_mod.load_state(_abs(cfg["paths"]["state_file"]))
    topics = state["papers"].get(paper.id, {}).get("topics", [])
    episodes = episodes_client.fetch_episode_audio(cfg["inputs"]["episodes_url"])

    ok = slack_client.post_paper(
        webhook, paper, summary, topics, episodes.get(paper.id)
    )
    print(f"slack-test: {'posted' if ok else 'FAILED'} {key} to the webhook")
    return 0 if ok else 1


# --- CLI ------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="fg-zettelkasten", description=__doc__)
    parser.add_argument("--config", default="config.yml", help="path to config.yml")
    sub = parser.add_subparsers(dest="command", required=True)

    p_bootstrap = sub.add_parser("bootstrap", help="process the whole archive (run once)")
    p_bootstrap.add_argument(
        "--limit", type=int, default=None, help="process only the first N papers"
    )

    p_update = sub.add_parser("update", help="incremental daily run")
    p_update.add_argument(
        "--recluster", action="store_true", help="also run a full re-cluster"
    )

    sub.add_parser("refresh-topics", help="rebuild the topic register from github.io")
    sub.add_parser("recluster", help="force a full re-cluster")
    sub.add_parser("fix-links", help="repair/de-link unresolved [[wikilinks]] in the vault")

    p_slack = sub.add_parser(
        "slack-test", help="post one paper's digest to the Slack webhook"
    )
    p_slack.add_argument("bibtex_key", help="bibtex key of a paper already processed")
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    cfg = load_config(args.config)

    commands = {
        "bootstrap": cmd_bootstrap,
        "update": cmd_update,
        "refresh-topics": cmd_refresh_topics,
        "recluster": cmd_recluster,
        "fix-links": cmd_fix_links,
        "slack-test": cmd_slack_test,
    }
    return commands[args.command](cfg, args) or 0


if __name__ == "__main__":
    sys.exit(main())
